services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=something_secret
      - POSTGRES_DB=banko_indiana
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7.4-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "9091:9091"
    environment:
      - DB_SOURCE=postgresql://root:something_secret@postgres:5432/banko_indiana?sslmode=disable
      - GRPC_SERVER_ADDRESS=api:9091
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
volumes:
  data-volume: