name: Go-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:16.2
            env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: something_secret
                POSTGRES_DB: banko_indiana
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 5432:5432
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install golang-migrate
      run: |
        echo "Current Architecture: $(dpkg --print-architecture)"
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-arm64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run DB migrations
      run: make migrateup

    - name: Test
      run: make test