name: Go-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres@16.2
            env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: something_secret
                POSTGRES_DB: banko_indiana
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install golang-migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@4.17.1

    - name: Run DB migrations
      run: make migrateup

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Test
      run: make test